version: "2"
services:
  serv:
    build: gril-app-server/.
    ports:
      - "5000:5000"
    depends_on:
       - db
  db:
    image: "postgres"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "grill-testpass"
      
 